#!/usr/bin/env python3
from __future__ import annotations

import argparse
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[1]
DEFAULT_STACKCHAN_DIR = ROOT_DIR / "projects" / "StackChan"
DEFAULT_SECRET_DIR = ROOT_DIR / "workspace" / "stackchan-secrets" / "server"
DEFAULT_SERVER_URL = "http://162.211.181.150"


def cpp_raw_string(value: str, tag: str) -> str:
    if len(tag) > 16:
        raise ValueError(f"C++ raw string delimiter is too long: {tag}")
    return f'R"{tag}({value}){tag}"'


def read_text_required(path: Path) -> str:
    if not path.is_file():
        raise RuntimeError(f"missing required file: {path}")
    return path.read_text(encoding="utf-8").strip() + "\n"


def update_kconfig_value(path: Path, key: str, value: str) -> None:
    lines = path.read_text(encoding="utf-8").splitlines() if path.exists() else []
    rendered = f'{key}="{value}"'
    updated = False
    new_lines: list[str] = []
    for line in lines:
        if line.startswith(f"{key}="):
            new_lines.append(rendered)
            updated = True
        else:
            new_lines.append(line)
    if not updated:
        if new_lines and new_lines[-1] != "":
            new_lines.append("")
        new_lines.append(rendered)
    path.write_text("\n".join(new_lines) + "\n", encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate ignored StackChan firmware secret config from local public keys."
    )
    parser.add_argument("--stackchan-dir", type=Path, default=DEFAULT_STACKCHAN_DIR)
    parser.add_argument("--secret-dir", type=Path, default=DEFAULT_SECRET_DIR)
    parser.add_argument("--server-url", default=DEFAULT_SERVER_URL)
    args = parser.parse_args()

    stackchan_dir = args.stackchan_dir.expanduser().resolve()
    firmware_dir = stackchan_dir / "firmware"
    if not firmware_dir.is_dir():
        raise RuntimeError(f"missing firmware directory: {firmware_dir}")

    secret_dir = args.secret_dir.expanduser().resolve()
    key_dir = secret_dir / "keys"
    server_public = read_text_required(key_dir / "server_public.pem")
    blue_public = read_text_required(key_dir / "stackchan_blue_public.pem")

    header_path = firmware_dir / "main" / "hal" / "local_secret_config.h"
    header_path.write_text(
        "\n".join(
            [
                "#pragma once",
                "",
                "// Generated by scripts/stackchan_generate_firmware_secrets.py.",
                "// This file is local-only and must stay ignored by git.",
                f"static constexpr const char* STACKCHAN_LOCAL_SERVER_URL = {cpp_raw_string(args.server_url, 'STACKCHAN_URL')};",
                f"static constexpr const char* STACKCHAN_LOCAL_SERVER_PUBLIC_KEY_PEM = {cpp_raw_string(server_public, 'SC_SERVER_PEM')};",
                f"static constexpr const char* STACKCHAN_LOCAL_BLUE_PUBLIC_KEY_PEM = {cpp_raw_string(blue_public, 'SC_BLUE_PEM')};",
                "",
            ]
        ),
        encoding="utf-8",
    )
    header_path.chmod(0o600)

    defaults_local = firmware_dir / "sdkconfig.defaults.local"
    update_kconfig_value(defaults_local, "CONFIG_STACKCHAN_SERVER_URL", args.server_url)

    sdkconfig = firmware_dir / "sdkconfig"
    if sdkconfig.exists():
        update_kconfig_value(sdkconfig, "CONFIG_STACKCHAN_SERVER_URL", args.server_url)

    print(f"Wrote local firmware config: {header_path}")
    print(f"Updated local firmware server URL: {args.server_url}")
    print("No private keys were written to source-controlled files.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
